/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../app/component/common/pageNotFoundComponent.component';
const styles_PageNotFoundComponent:any[] = ([] as any[]);
export const RenderType_PageNotFoundComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PageNotFoundComponent,
  data: {}
}
);
function View_PageNotFoundComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ' ',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.errorCode;
    const currVal_1:any = co.errorMessage;
    ck(v,1,0,currVal_0,currVal_1);
  });
}
export function View_PageNotFoundComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_PageNotFoundComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['page not found']))
  ]
  ,(ck,v) => {
    var co:import2.PageNotFoundComponent = v.component;
    const currVal_0:any = co.errorCode;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_PageNotFoundComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'error-page',([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,RenderType_PageNotFoundComponent)),
    import0.ɵdid(24576,(null as any),0,import2.PageNotFoundComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PageNotFoundComponentNgFactory:import0.ComponentFactory<import2.PageNotFoundComponent> = import0.ɵccf('error-page',import2.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovanMvcXVpY2tzdGFydC9zcmMvYXBwL2NvbXBvbmVudC9jb21tb24vcGFnZU5vdEZvdW5kQ29tcG9uZW50LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9qcy9xdWlja3N0YXJ0L3NyYy9hcHAvY29tcG9uZW50L2NvbW1vbi9wYWdlTm90Rm91bmRDb21wb25lbnQuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovanMvcXVpY2tzdGFydC9zcmMvYXBwL2NvbXBvbmVudC9jb21tb24vcGFnZU5vdEZvdW5kQ29tcG9uZW50LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovanMvcXVpY2tzdGFydC9zcmMvYXBwL2NvbXBvbmVudC9jb21tb24vcGFnZU5vdEZvdW5kQ29tcG9uZW50LmNvbXBvbmVudC50cy5QYWdlTm90Rm91bmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDIgKm5nSWY9XCJlcnJvckNvZGVcIj57e2Vycm9yQ29kZX19IHt7ZXJyb3JNZXNzYWdlfX08L2gyPlxyXG48aDI+cGFnZSBub3QgZm91bmQ8L2gyPiIsIjxlcnJvci1wYWdlPjwvZXJyb3ItcGFnZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQXNCO01BQUE7TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUFBO0lBQUE7SUFBQTs7Ozs7SUFBdEI7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF5RDtJQUN6RDtJQUFJOzs7O0lBREE7SUFBSixTQUFJLFNBQUo7Ozs7O0lDQUE7Z0JBQUE7Ozs7In0=
