/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%]{\n  border-bottom: 1px solid gray;\n  border-left: 1px solid gray;\n  border-right: 1px solid gray;\n  width:195px;\n  height: 16px;\n  padding: 5px;\n  background-color: white;\n  cursor: pointer;\n}\n\n.search-result[_ngcontent-%COMP%]:hover {\n  color: #eee;\n  background-color: #607D8B;\n}\n\n#search-box[_ngcontent-%COMP%]{\n  width: 200px;\n  height: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovanMvcXVpY2tzdGFydC9zcmMvYXBwL2NvbXBvbmVudC9zZWFyY2gvaGVyby1zZWFyY2guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9qcy9xdWlja3N0YXJ0L3NyYy9hcHAvY29tcG9uZW50L3NlYXJjaC9oZXJvLXNlYXJjaC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
